### ISSUE TITLE
Make a research and testing of TC

### ISSUE THREAD

**Issue by mehalyna** [mehalyna/Wr-52.TAQC-Python-TestProject#3]
https://github.com/ita-social-projects/EventsExpress/issues/1129
https://github.com/ita-social-projects/EventsExpress/issues/1154

**Comment by servettonga** [comment]
### Description
When the user navigates to the landing page, a changeable background is present. The background photo changes every 5 seconds.

S# | Action | Test Data | Expected Result | Actual Result | P/F | Automated
-- | -- | -- | -- | -- | -- | --
1 | Navigate to https://eventsexpress-test.azurewebsites.net/landing |   | The user is transferred to landing page | Landing Page | P |  Y
2 | Calculate, how often the background is being changed, using timer |   | The background of the landing page changes every 5 seconds | 5  | P |  Y

<br>

### Description
When the user clicks on the ‘Events Express’ button in the upper left corner, they are transferred to the Home page.

S# | Action | Test Data | Expected Result | Actual Result | P/F | Automated
-- | -- | -- | -- | -- | -- | --
1 | Click on 'Events Express' button in the top left corner |   | The user is transferred to the Home page | Home Page | P |  Y
